name: IntegrationTest
on:
  workflow_call:

jobs:
  integration-test:
    name: IntegrationTest
    runs-on:
      - self-hosted
      - k8s-api
      - linux-amd64-2-4096
      - burstable
      - linux-amd64-s

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: IntegrationTest
        id: build
        run: |
          echo "This is a IntegrationTest stage"
